#dataSource
server:
 port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 456789
    url: jdbc:mysql://localhost:3306/epidemic?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC


  #thymeleaf cache close
  thymeleaf:
    cache: false
#pojo package typealiases
mybatis:
  type-aliases-package: com.zywl.pojo




